img=imread('flowers.jpg');
[r,g,b]= imsplit(img);
R= imhist(r);
G= imhist(g);
B= imhist(b);
subplot(1,2,1);
imshow(img);
title('Image');
subplot(1,2,2);
plot(G,'g');
hold on;
plot(R,'r');
plot(B,'b');
hold off;
title('Histogram');
