img= imread('lowcontrast1.jpeg');
subplot(4,2,1);
imshow(img);
title('Original Low Contrast Image');
low_cont = img-120;
subplot(4,2,2);
imshow(low_cont);
title('Low Contrast Dark Image');
img2= imread('highcontrast.jpeg');
subplot(4,2,5);
imshow(img2);
title('High Contrast Image');
img3= img+100;
subplot(4,2,6);
imshow(img3);
title('Low Contrast Light Image');
subplot(4,2,3);
imhist(img);
title('Original Low Contrast Image Histogram');
subplot(4,2,4);
imhist(low_cont);
title('Dark Image Histogram');
subplot(4,2,7);
imhist(img2);
title('High Contrast Image Histogram');
subplot(4,2,8);
imhist(img3);
title('Light Image Histogram');